//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosMunicipio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraAccesoSistemas
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> ALTAREGISTROTABLA { get; set; }
        public string CVE_CAT_EST { get; set; }
        public string CVE_CAT_ORI { get; set; }
        public string NOMBRE_O_RAZON_SOCIAL { get; set; }
        public string APELLIDO_PATERNO { get; set; }
        public string APELLIDO_MATERNO { get; set; }
        public string USUARIOALTA { get; set; }
        public string IP_ALTA { get; set; }
        public string TERMINALALTA { get; set; }
        public string APLICATIVO { get; set; }
        public string URL { get; set; }
        public string DESCRIPCION { get; set; }
    }
}
