//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosMunicipio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Municipio
    {
        public int Id { get; set; }
        public string Municipio { get; set; }
        public int Clave { get; set; }
        public bool Activo { get; set; }
        public int FK_Estado { get; set; }
        public string BD { get; set; }
    }
}
