//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosMunicipio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GDB01001Entities : DbContext
    {
        public GDB01001Entities()
            : base("name=GDB01001Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAT_LOCALIDAD> CAT_LOCALIDAD { get; set; }
        public virtual DbSet<SIS_ASENTAMIENTOS> SIS_ASENTAMIENTOS { get; set; }
        public virtual DbSet<SIS_PC_CLAVE_CATASTRAL> SIS_PC_CLAVE_CATASTRAL { get; set; }
        public virtual DbSet<SIS_PC_PROPIETARIOS> SIS_PC_PROPIETARIOS { get; set; }
        public virtual DbSet<SIS_PC_UBICACION> SIS_PC_UBICACION { get; set; }
    }
}
