//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosMunicipio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIS_TRACAT_ABSTENCIONES
    {
        public int ID { get; set; }
        public string STATUSREGISTROTABLA { get; set; }
        public Nullable<System.DateTime> ALTAREGISTROTABLA { get; set; }
        public Nullable<System.DateTime> BAJAREGISTROTABLA { get; set; }
        public string USUARIOBAJA { get; set; }
        public string USUARIOALTA { get; set; }
        public string CVE_CAT_EST { get; set; }
        public string CVE_CAT_ORI { get; set; }
        public string OBS { get; set; }
        public string PISO { get; set; }
        public string OBS_ELIMINAR { get; set; }
    }
}
