//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosMunicipio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIS_ASENTAMIENTOS
    {
        public int OBJECTID { get; set; }
        public Nullable<int> CLAVEUNICA { get; set; }
        public string STATUSREGISTROTABLA { get; set; }
        public Nullable<System.DateTime> ALTAREGISTROTABLA { get; set; }
        public Nullable<System.DateTime> BAJAREGISTROTABLA { get; set; }
        public string HORAALTAREGISTROTABLA { get; set; }
        public string HORABAJAREGISTROTABLA { get; set; }
        public string USUARIOALTA { get; set; }
        public string USUARIOBAJA { get; set; }
        public string TERMINALALTA { get; set; }
        public string TERMINALBAJA { get; set; }
        public string CVE_ENTIDAD { get; set; }
        public string CVE_REGION_CATASTRAL { get; set; }
        public string CVE_MUNICIPIO { get; set; }
        public string CVE_ZONA_CATASTRAL { get; set; }
        public string CVE_LOCALIDAD { get; set; }
        public string CVE_SECTOR_CATASTRAL { get; set; }
        public string CVE_ASENTAMIENTO { get; set; }
        public string TIPO_ASENTAMIENTO { get; set; }
        public string NOMBRE_ASENTAMIENTO { get; set; }
        public string CP { get; set; }
        public string NOMBRE_COMPLETO_ASENTAMIENTO { get; set; }
        public string OBSERVACIONES { get; set; }
    }
}
