//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosMunicipio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIS_PC_CLAVE_CATASTRAL
    {
        public int OBJECTID { get; set; }
        public Nullable<int> CLAVEUNICA { get; set; }
        public string STATUSREGISTROTABLA { get; set; }
        public Nullable<System.DateTime> ALTAREGISTROTABLA { get; set; }
        public Nullable<System.DateTime> BAJAREGISTROTABLA { get; set; }
        public string HORAALTAREGISTROTABLA { get; set; }
        public string HORABAJAREGISTROTABLA { get; set; }
        public string USUARIOALTA { get; set; }
        public string USUARIOBAJA { get; set; }
        public string TERMINALALTA { get; set; }
        public string TERMINALBAJA { get; set; }
        public string CVE_CAT_EST { get; set; }
        public string CVE_CAT_ORI { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public string CVE_CAT_EST_ANT { get; set; }
        public string CVE_CAT_ANT { get; set; }
        public string CVE_PREDIAL { get; set; }
        public string REGIMEN_PREDIAL { get; set; }
        public Nullable<System.DateTime> FCH_INSCRIP_RPP { get; set; }
        public string FOLIO_REAL { get; set; }
        public string LEVANTAMIENTO { get; set; }
        public string TD { get; set; }
        public string MANIFESTACION { get; set; }
        public string TITULO_RAN { get; set; }
        public string VOLUMEN { get; set; }
        public string ESCRITURA { get; set; }
    }
}
