//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosMunicipio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIS_PC_UBICACION
    {
        public int OBJECTID { get; set; }
        public Nullable<int> CLAVEUNICA { get; set; }
        public string STATUSREGISTROTABLA { get; set; }
        public Nullable<System.DateTime> ALTAREGISTROTABLA { get; set; }
        public Nullable<System.DateTime> BAJAREGISTROTABLA { get; set; }
        public string HORAALTAREGISTROTABLA { get; set; }
        public string HORABAJAREGISTROTABLA { get; set; }
        public string USUARIOALTA { get; set; }
        public string USUARIOBAJA { get; set; }
        public string TERMINALALTA { get; set; }
        public string TERMINALBAJA { get; set; }
        public string CVE_CAT_EST { get; set; }
        public string CVE_CAT_ORI { get; set; }
        public string CVE_ENTIDAD { get; set; }
        public string NOM_ENTIDAD { get; set; }
        public string CVE_REGION_CATASTRAL { get; set; }
        public string CVE_MUNICIPIO { get; set; }
        public string NOM_MUNICIPIO { get; set; }
        public string CVE_ZONA_CATASTRAL { get; set; }
        public string CVE_LOCALIDAD { get; set; }
        public string NOM_LOCALIDAD { get; set; }
        public string CVE_SECTOR_CATASTRAL { get; set; }
        public string CVE_ASENTAMIENTO { get; set; }
        public string TIPO_ASENTAMIENTO { get; set; }
        public string NOMBRE_ASENTAMIENTO { get; set; }
        public string CP { get; set; }
        public string NOMBRE_COMPLETO_ASENTAMIENTO { get; set; }
        public string CVE_VIALIDAD { get; set; }
        public string TIPO_VIALIDAD { get; set; }
        public string NOMBRE_VIALIDAD { get; set; }
        public string NOMBRE_COMPLETO_VIALIDAD { get; set; }
        public string MANZANA { get; set; }
        public string LOTE { get; set; }
        public string NUMERO_EXTERIOR { get; set; }
        public string NUMERO_INTERIOR { get; set; }
        public string EDIFICIO_NOMBRE { get; set; }
        public string DESCRIPCION_UBICACION { get; set; }
        public string ID_CONDOMINIO { get; set; }
        public string NOMBRE_CONDOMINIO { get; set; }
        public Nullable<short> NIVEL { get; set; }
        public string CARTOG_NOM_DIV { get; set; }
        public string CVE_VIACOM { get; set; }
        public string VIACOM_NOM { get; set; }
        public string VIACOM_TERM_GEN { get; set; }
        public string VIACOM_ADMON { get; set; }
        public string VIACOM_DER_TRANS { get; set; }
        public Nullable<short> VIACOM_CODIGO { get; set; }
        public string CARRETERA_TRAMO { get; set; }
        public string CAMINO_TRAMO { get; set; }
        public string CARRETERA_CADENA { get; set; }
        public string CAMINO_CADENA { get; set; }
        public string CAMINO_MARGEN { get; set; }
        public string CVE_NA { get; set; }
        public string NOM_NA { get; set; }
        public string NUM_POL { get; set; }
        public string NUM_ZONA_TUC { get; set; }
        public string NUM_PARCELA { get; set; }
        public string IGUALUN { get; set; }
        public string UBI_OBSERVACIONES { get; set; }
    }
}
