//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosMunicipio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIS_PC_PROPIETARIOS
    {
        public int OBJECTID { get; set; }
        public Nullable<int> CLAVEUNICA { get; set; }
        public string STATUSREGISTROTABLA { get; set; }
        public Nullable<System.DateTime> ALTAREGISTROTABLA { get; set; }
        public Nullable<System.DateTime> BAJAREGISTROTABLA { get; set; }
        public string HORAALTAREGISTROTABLA { get; set; }
        public string HORABAJAREGISTROTABLA { get; set; }
        public string USUARIOALTA { get; set; }
        public string USUARIOBAJA { get; set; }
        public string TERMINALALTA { get; set; }
        public string TERMINALBAJA { get; set; }
        public string CVE_CAT_EST { get; set; }
        public string CVE_CAT_ORI { get; set; }
        public Nullable<int> ID_PROPIETARIO { get; set; }
        public string TIPO_PROPIETARIO { get; set; }
        public string TIPO_PERSONA { get; set; }
        public string APELLIDO_PATERNO { get; set; }
        public string APELLIDO_MATERNO { get; set; }
        public string NOMBRE_O_RAZON_SOCIAL { get; set; }
        public string CURP { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public string LUGAR_NACIMIENTO { get; set; }
        public string RFC { get; set; }
        public Nullable<decimal> PORCENTAJE_POSESION { get; set; }
        public string TELEFONO { get; set; }
        public string CORREO_ELECTRONICO { get; set; }
        public Nullable<int> TIPO_PERSONA_VULNERABLE { get; set; }
        public string PROPIETARIO_ORIGINAL { get; set; }
        public string APELLIDO_PATERNO_HIG { get; set; }
        public string APELLIDO_MATERNO_HIG { get; set; }
        public string NOMBRE_O_RAZON_SOCIAL_HIG { get; set; }
        public string PROP_OBSERVACIONES { get; set; }
        public string FOLIO_TD { get; set; }
        public Nullable<decimal> MONTO_OPERACION_TD { get; set; }
        public string NUMERO_DIPI { get; set; }
        public Nullable<System.DateTime> FECHA_DIPI { get; set; }
    }
}
