//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosMunicipio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioPropietario
    {
        public int Id { get; set; }
        public string FK_NombreUsuario { get; set; }
        public string FK_CuentaCatastralEstandar { get; set; }
        public string FK_CuentaCatastralOriginal { get; set; }
        public string Propietario { get; set; }
        public string CoPropietario { get; set; }
        public bool Habilitado { get; set; }
    }
}
