//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosMunicipio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Id { get; set; }
        public string NombreCompleto { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string NombreUsuario { get; set; }
        public string Contrasena { get; set; }
        public int FK_Puesto { get; set; }
        public int FK_Coordinacion { get; set; }
        public bool SistemaTramites { get; set; }
        public bool SistemaCatastral { get; set; }
        public bool SistemaVisualizador { get; set; }
        public bool Habilitado { get; set; }
        public byte[] Fotografia { get; set; }
        public Nullable<int> NumeroControl { get; set; }
        public Nullable<bool> Analista { get; set; }
        public Nullable<bool> Recepcionista { get; set; }
        public string CorreoElectronico { get; set; }
        public string ContrasenaInicial { get; set; }
        public string Celular { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaActivacion { get; set; }
        public Nullable<int> FK_Cat_Municipio { get; set; }
        public Nullable<bool> PagoDerechos { get; set; }
        public Nullable<int> FK_Cat_Perfil { get; set; }
        public string VersionSDE { get; set; }
        public string TipoSolicitante { get; set; }
        public Nullable<int> NumNotaria { get; set; }
        public string Vialidad { get; set; }
        public string NumInterior { get; set; }
        public string NumExterior { get; set; }
        public string NombreColonia { get; set; }
        public string CP { get; set; }
        public string NombreLocalidad { get; set; }
        public string NombreEntidad { get; set; }
        public string ID_PISABIT { get; set; }
        public Nullable<bool> SesionActiva { get; set; }
        public bool SesionActivaConsulta { get; set; }
        public Nullable<System.DateTime> UltimaSesion { get; set; }
        public Nullable<int> Puesto { get; set; }
        public string Descripcion_Puesto { get; set; }
    }
}
