//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosMunicipio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WFTRAMITESEntities : DbContext
    {
        public WFTRAMITESEntities()
            : base("name=WFTRAMITESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cat_Municipio> Cat_Municipio { get; set; }
        public virtual DbSet<Cat_Acceso> Cat_Acceso { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
